/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.4 */

#include "mangohud.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Message, Message, 2)


PB_BIND(Alive, Alive, AUTO)


PB_BIND(Architecture, Architecture, AUTO)


PB_BIND(RenderInfo, RenderInfo, AUTO)


PB_BIND(BlackListInfo, BlackListInfo, AUTO)


PB_BIND(ConfigRequest, ConfigRequest, AUTO)


PB_BIND(ConfigReload, ConfigReload, AUTO)


PB_BIND(Config, Config, AUTO)


PB_BIND(Config_HudGeometry, Config_HudGeometry, AUTO)


PB_BIND(Config_Element, Config_Element, AUTO)


PB_BIND(Config_Key, Config_Key, AUTO)


PB_BIND(Timestamp, Timestamp, AUTO)


PB_BIND(FrameTime, FrameTime, AUTO)


PB_BIND(GpuInfo, GpuInfo, AUTO)


PB_BIND(CpuInfo, CpuInfo, AUTO)


PB_BIND(MemInfo, MemInfo, AUTO)


PB_BIND(GpuInfoApp, GpuInfoApp, AUTO)


PB_BIND(CpuInfoApp, CpuInfoApp, AUTO)


PB_BIND(MemInfoApp, MemInfoApp, AUTO)




